#!/bin/sh

echo HEEEEEEEEEEEEEEEEEEEEEEEEEEELO!

FILE=$(echo NVIDIA-Linux*.run)
DIR=$(basename $FILE .run)
VERSION=$(echo $FILE | awk -F - "{ print \$4 }")

set -x

mkdir tls
mkdir -p vulkan/icd.d
mkdir -p glvnd/egl_vendor.d

chmod a+x $FILE
./$FILE -a -x
rm $FILE

cd $DIR

# GLVND
rm libGL.so*
rm libEGL.so*

# Simple wildcard install of libs
mv lib*.so.$VERSION ..
if [ -d tls ]; then
   mv tls/lib*.so.$VERSION ..
fi

mv nvidia_icd.json ../vulkan/icd.d/
mv 10_nvidia.json ../glvnd/egl_vendor.d/

cd ..

rm -rf $DIR

# default to nvidia
ln -s libGLX_nvidia.so.$VERSION libGLX_indirect.so.0

# Fix unowned lib links
ln -s libEGL_nvidia.so.$VERSION libEGL_nvidia.so.0
ln -s libGLESv2_nvidia.so.$VERSION libGLESv2_nvidia.so.2
ln -s libGLX_nvidia.so.$VERSION libGLX_nvidia.so.0
