name: build
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder ostree make
          flatpak remote-add --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          # Only build a single version to speed up CI.
          echo 'DRIVER_VERSIONS="${BETA_VERSIONS%% *}"' >> versions.sh
          make
