name: Flathub build

concurrency:
  group: flathub-build
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up build matrix
        id: set-matrix
        run: |
          source versions.sh
          export DRIVER_VERSIONS
          python3 setup-matrix.py

  build:
    needs: setup-matrix
    name: ${{ matrix.arch }}-build-batch-${{ matrix.id }}
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
      fail-fast: true
    steps:
      - name: Create work directory
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/work
          chmod 777 ${GITHUB_WORKSPACE}/work

      - name: Free up disk space
        run: |
          sudo rm -rf /opt/ghc /usr/local/.ghcup || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo rm -rf /swapfile || true
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet /usr/share/swift
          sudo rm -rf /usr/local/share/boost /usr/local/share/powershell
          sudo rm -rf /usr/lib/google-cloud-sdk /usr/lib/jvm
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Download justfile
        run: |
          docker run --rm --privileged \
            --entrypoint="" \
            -v "${GITHUB_WORKSPACE}/work:/work" \
            -w /work \
            ghcr.io/flathub-infra/flatpak-builder-lint:latest \
            curl https://raw.githubusercontent.com/flathub-infra/vorarbeiter/refs/heads/main/justfile -o justfile

      - name: Checkout repository
        run: |
          docker run --rm --privileged \
            --entrypoint="" \
            -v "${GITHUB_WORKSPACE}/work:/work" \
            -w /work \
            -e REPO \
            -e REF \
            ghcr.io/flathub-infra/flatpak-builder-lint:latest \
            /bin/bash -c '
              just checkout https://github.com/${{ github.repository }} ${{ github.ref }}
            '

      - name: Build flatpak
        run: |
          docker run --rm --privileged \
            --entrypoint="" \
            -v "${GITHUB_WORKSPACE}/work:/work" \
            -w /work \
            -e APP_ID \
            -e BRANCH \
            ghcr.io/flathub-infra/flatpak-builder-lint:latest \
            /bin/bash -c '
              just prepare-env
              export DRIVER_VERSIONS="${{ matrix.versions }}"
              make
            '
      - name: Generate deltas
        run: |
          docker run --rm --privileged \
            --entrypoint="" \
            -v "${GITHUB_WORKSPACE}/work:/work" \
            -w /work \
            ghcr.io/flathub-infra/flatpak-builder-lint:latest \
            just generate-deltas

      - name: Upload and publish build
        run: |
          docker run --rm --privileged \
            --entrypoint="" \
            -v "${GITHUB_WORKSPACE}/work:/work" \
            -w /work \
            -e REPO_TOKEN=${{ secrets.REPO_TOKEN }} \
            ghcr.io/flathub-infra/flatpak-builder-lint:latest \
            /bin/bash -c '
               flat-manager-client create https://hub.flathub.org stable --build-log-url https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} > build_url
               flat-manager-client push $(<build_url) repo
               flat-manager-client commit $(<build_url)
               flat-manager-client publish $(<build_url)
            '
